# Generated by Django 4.2.2 on 2024-04-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountProfile", "0009_block"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="device_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="latitude",
            field=models.CharField(blank=True, max_length=2505, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="longitude",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
