# Generated by Django 4.2.2 on 2024-06-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountProfile", "0011_alter_customuser_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="languages",
        ),
        migrations.AddField(
            model_name="customuser",
            name="languages",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
