# Generated by Django 4.2.2 on 2024-07-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountProfile", "0013_alter_chatmessage_options_chatmessage_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tokens", models.TextField(help_text="JSON-encoded list of tokens")),
                (
                    "notification_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("info", "Information"),
                            ("warning", "Warning"),
                            ("alert", "Alert"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("body", models.TextField(blank=True, null=True)),
                ("doc_id", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("image", models.URLField(blank=True, null=True)),
                ("user", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
