# Generated by Django 4.2.2 on 2024-07-15 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accountProfile", "0014_notification"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="tokens",
            new_name="token",
        ),
    ]
