# Generated by Django 4.2.2 on 2024-07-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountProfile", "0016_customuser_is_online_customuser_last_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="languages",
        ),
        migrations.AddField(
            model_name="customuser",
            name="languages",
            field=models.ManyToManyField(
                blank=True, null=True, to="accountProfile.language"
            ),
        ),
    ]
