# Generated by Django 4.2.2 on 2024-08-29 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accountProfile",
            "0018_notification_created_at_notification_is_read_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
