# Generated by Django 4.2.2 on 2024-08-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountProfile", "0019_alter_customuser_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="languages",
            field=models.ManyToManyField(blank=True, to="accountProfile.language"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_active",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="latitude",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
