# Generated by Django 4.2.2 on 2024-09-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountProfile", "0020_alter_customuser_is_online_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("info", "Information"),
                    ("warning", "Warning"),
                    ("alert", "Alert"),
                    ("chat", "Chat"),
                    ("chat", "Chat"),
                    ("general", "General"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
