# Generated by Django 3.2.15 on 2024-10-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountProfile", "0021_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("info", "Information"),
                    ("warning", "Warning"),
                    ("alert", "Alert"),
                    ("chat", "Chat"),
                    ("post", "Post"),
                    ("general", "General"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
