# Generated by Django 3.2.15 on 2024-10-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountProfile", "0022_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="information",
            field=models.TextField(blank=True, null=True),
        ),
    ]
