# Generated by Django 3.2.15 on 2024-10-31 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountProfile', '0023_customuser_information'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
    ]
