# Generated by Django 4.2.2 on 2023-09-07 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarModel',
            new_name='PostType',
        ),
        migrations.RenameModel(
            old_name='CarMaker',
            new_name='Subcategory',
        ),
        migrations.RenameField(
            model_name='vehiclepost',
            old_name='car_model',
            new_name='post_type',
        ),
        migrations.RenameField(
            model_name='vehiclepost',
            old_name='car_maker',
            new_name='sub_category',
        ),
    ]
