# Generated by Django 4.2.2 on 2023-09-07 05:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accountProfile", "0001_initial"),
        ("post", "0002_rename_carmodel_posttype_rename_carmaker_subcategory_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="VehiclePost",
            new_name="Post",
        ),
    ]
