# Generated by Django 4.2.2 on 2023-12-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0014_alter_post_category_alter_post_city_alter_post_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="condition",
            name="delete",
            field=models.BooleanField(default=False),
        ),
    ]
