# Generated by Django 4.2.2 on 2023-12-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0015_condition_delete"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="condition",
            name="delete",
        ),
        migrations.AddField(
            model_name="post",
            name="delete",
            field=models.BooleanField(default=False),
        ),
    ]
