# Generated by Django 4.2.2 on 2024-02-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportchat',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='report_chat/audio'),
        ),
        migrations.AddField(
            model_name='reportchat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='report_chat'),
        ),
    ]
