# Generated by Django 4.2.2 on 2024-03-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0026_regionspecs_post_region_specs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='kilometers',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
