# Generated by Django 4.2.2 on 2024-04-15 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0028_boostrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at']},
        ),
    ]
