# Generated by Django 4.2.2 on 2024-04-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0029_alter_report_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="sold",
            field=models.BooleanField(default=False),
        ),
    ]
