# Generated by Django 4.2.2 on 2024-05-22 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0034_category_group_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="group_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories_in_group",
                to="post.imagegroupname",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="pre_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="post.precategory",
            ),
        ),
        migrations.AlterField(
            model_name="imagegroup",
            name="group_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image_groups",
                to="post.imagegroupname",
            ),
        ),
        migrations.AlterField(
            model_name="imagegroup",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images_in_group",
                to="post.postexampleimage",
            ),
        ),
    ]
