# Generated by Django 4.2.2 on 2024-06-13 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accountProfile", "0011_alter_customuser_email"),
        ("post", "0035_alter_category_group_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accountProfile.country",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
    ]
