# Generated by Django 4.2.2 on 2024-08-13 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0036_post_country_alter_post_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportchat",
            name="chat_type",
            field=models.CharField(
                choices=[("report", "Report"), ("support", "Support")],
                default="report",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="reportchat",
            name="report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_chats",
                to="post.report",
            ),
        ),
    ]
